//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagHierarchyManager.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagHierarchyManager.Assets.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive indent was detected at line {0}..
        /// </summary>
        internal static string ImporterMusicBeeIndentExcessive {
            get {
                return ResourceManager.GetString("ImporterMusicBeeIndentExcessive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneven indent was found at line {0}..
        /// </summary>
        internal static string ImporterMusicBeeIndentUneven {
            get {
                return ResourceManager.GetString("ImporterMusicBeeIndentUneven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process exited abruptly due to an error with handling the indent. (current line&apos;s indent level was greater than the amount of tags in the parent stack).
        /// </summary>
        internal static string ImporterMusicBeePopOutOfRange {
            get {
                return ResourceManager.GetString("ImporterMusicBeePopOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag hierarchy starts with a space, which is not valid for a tag hierarchy template&apos;s structure..
        /// </summary>
        internal static string ImporterMusicBeeStartsWithSpace {
            get {
                return ResourceManager.GetString("ImporterMusicBeeStartsWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab characters were detected, which is an invalid structure for MusicBee tag hierarchy templates..
        /// </summary>
        internal static string ImporterMusicBeeTabsDetected {
            get {
                return ResourceManager.GetString("ImporterMusicBeeTabsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting is required and cannot be deleted..
        /// </summary>
        internal static string TagDatabaseDeletingRequiredSetting {
            get {
                return ResourceManager.GetString("TagDatabaseDeletingRequiredSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usable parameters received..
        /// </summary>
        internal static string TagDatabaseEmptyParameters {
            get {
                return ResourceManager.GetString("TagDatabaseEmptyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path cannot be empty..
        /// </summary>
        internal static string TagDatabaseFilePathEmpty {
            get {
                return ResourceManager.GetString("TagDatabaseFilePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid SQLite database..
        /// </summary>
        internal static string TagDatabaseInvalidFile {
            get {
                return ResourceManager.GetString("TagDatabaseInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension must be .thdb..
        /// </summary>
        internal static string TagDatabaseInvalidFileExt {
            get {
                return ResourceManager.GetString("TagDatabaseInvalidFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid database file for the Tag Hierarchy Manager application..
        /// </summary>
        internal static string TagDatabaseInvalidStructure {
            get {
                return ResourceManager.GetString("TagDatabaseInvalidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag hierarchy database has not been initialised..
        /// </summary>
        internal static string TagDatabaseNotInitialised {
            get {
                return ResourceManager.GetString("TagDatabaseNotInitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting {0} already exists in the database..
        /// </summary>
        internal static string TagDatabaseSettingKeyExists {
            get {
                return ResourceManager.GetString("TagDatabaseSettingKeyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting {0} was not found in the settings table..
        /// </summary>
        internal static string TagDatabaseSettingKeyNotFound {
            get {
                return ResourceManager.GetString("TagDatabaseSettingKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute function on database due to SQLite error. Error code: {0}.
        /// </summary>
        internal static string TagDatabaseSqliteGeneric {
            get {
                return ResourceManager.GetString("TagDatabaseSqliteGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag requested has child tags and cannot currently be deleted. Delete its children first and try again..
        /// </summary>
        internal static string TagDatabaseTagHasChildren {
            get {
                return ResourceManager.GetString("TagDatabaseTagHasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag requested does not exist in the database..
        /// </summary>
        internal static string TagDatabaseTagNotFound {
            get {
                return ResourceManager.GetString("TagDatabaseTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} has no parents specified and is not top-level, which is invalid..
        /// </summary>
        internal static string TagNameIsBlank {
            get {
                return ResourceManager.GetString("TagNameIsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} has no parents specified and is not top-level, which is invalid..
        /// </summary>
        internal static string TagOrphanAttempt {
            get {
                return ResourceManager.GetString("TagOrphanAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} has itself in Parents, which is invalid..
        /// </summary>
        internal static string TagSelfParentAttempt {
            get {
                return ResourceManager.GetString("TagSelfParentAttempt", resourceCulture);
            }
        }
    }
}
