//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagHierarchyManager.UI.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagHierarchyManager.UI.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string AboutTitleFormat {
            get {
                return ResourceManager.GetString("AboutTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row....
        /// </summary>
        public static string BulkAddButtonAddRow {
            get {
                return ResourceManager.GetString("BulkAddButtonAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete row(s)....
        /// </summary>
        public static string BulkAddButtonDeleteRow {
            get {
                return ResourceManager.GetString("BulkAddButtonDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (on row {1}).
        /// </summary>
        public static string BulkAddExceptionTemplate {
            get {
                return ResourceManager.GetString("BulkAddExceptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tag....
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add multiple tags....
        /// </summary>
        public static string ButtonBulkAdd {
            get {
                return ResourceManager.GetString("ButtonBulkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is top level?.
        /// </summary>
        public static string CheckBoxTopLevel {
            get {
                return ResourceManager.GetString("CheckBoxTopLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) Flaky 2025, licensed under MIT.
        /// </summary>
        public static string CopyrightAndLicense {
            get {
                return ResourceManager.GetString("CopyrightAndLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string DatabaseSettingsDbVersion {
            get {
                return ResourceManager.GetString("DatabaseSettingsDbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default tag bindings:.
        /// </summary>
        public static string DatabaseSettingsDefaultTagBindings {
            get {
                return ResourceManager.GetString("DatabaseSettingsDefaultTagBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags: {0}, with {1} parent-child relationships.
        /// </summary>
        public static string DatabaseSettingsTagCount {
            get {
                return ResourceManager.GetString("DatabaseSettingsTagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose template to import....
        /// </summary>
        public static string DialogTitleChooseImportTemplate {
            get {
                return ResourceManager.GetString("DialogTitleChooseImportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export tag database to file....
        /// </summary>
        public static string DialogTitleExportTagDatabase {
            get {
                return ResourceManager.GetString("DialogTitleExportTagDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open tag database....
        /// </summary>
        public static string DialogTitleOpenDatabase {
            get {
                return ResourceManager.GetString("DialogTitleOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save tag database file....
        /// </summary>
        public static string DialogTitleSaveDatabaseAs {
            get {
                return ResourceManager.GetString("DialogTitleSaveDatabaseAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be blank..
        /// </summary>
        public static string ErrorBlankTagName {
            get {
                return ResourceManager.GetString("ErrorBlankTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialogTitleBarTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitleBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string ErrorImportFileTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorImportFileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags that are not top level must have a parent..
        /// </summary>
        public static string ErrorOrphanTagAttempt {
            get {
                return ResourceManager.GetString("ErrorOrphanTagAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot make tags a parent of themselves..
        /// </summary>
        public static string ErrorSelfParentAttempt {
            get {
                return ResourceManager.GetString("ErrorSelfParentAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicBee tag hierarchy template.
        /// </summary>
        public static string FileFormatMusicBeeTagHierarchy {
            get {
                return ResourceManager.GetString("FileFormatMusicBeeTagHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag hierarchy database.
        /// </summary>
        public static string FileFormatTagHierarchyDatabase {
            get {
                return ResourceManager.GetString("FileFormatTagHierarchyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias(es).
        /// </summary>
        public static string HeaderAliases {
            get {
                return ResourceManager.GetString("HeaderAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added.
        /// </summary>
        public static string HeaderDateAdded {
            get {
                return ResourceManager.GetString("HeaderDateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string HeaderDateModified {
            get {
                return ResourceManager.GetString("HeaderDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string HeaderNotes {
            get {
                return ResourceManager.GetString("HeaderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent(s).
        /// </summary>
        public static string HeaderParents {
            get {
                return ResourceManager.GetString("HeaderParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag binding(s).
        /// </summary>
        public static string HeaderTagBindings {
            get {
                return ResourceManager.GetString("HeaderTagBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file to save to:.
        /// </summary>
        public static string ImportDatabaseToSave {
            get {
                return ResourceManager.GetString("ImportDatabaseToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to import:.
        /// </summary>
        public static string ImportFileToImport {
            get {
                return ResourceManager.GetString("ImportFileToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file picked..
        /// </summary>
        public static string ImportNoFilePicked {
            get {
                return ResourceManager.GetString("ImportNoFilePicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed..
        /// </summary>
        public static string ImportStatusFailed {
            get {
                return ResourceManager.GetString("ImportStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        public static string ImportStatusInProgress {
            get {
                return ResourceManager.GetString("ImportStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Database.
        /// </summary>
        public static string MenuDatabase {
            get {
                return ResourceManager.GetString("MenuDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database _settings.
        /// </summary>
        public static string MenuItemDatabaseSettings {
            get {
                return ResourceManager.GetString("MenuItemDatabaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        public static string MenuItemExport {
            get {
                return ResourceManager.GetString("MenuItemExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New from import....
        /// </summary>
        public static string MenuItemImport {
            get {
                return ResourceManager.GetString("MenuItemImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New database.
        /// </summary>
        public static string MenuItemNewDatabase {
            get {
                return ResourceManager.GetString("MenuItemNewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MenuItemOpen {
            get {
                return ResourceManager.GetString("MenuItemOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string MenuItemQuit {
            get {
                return ResourceManager.GetString("MenuItemQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently added/edited tags.
        /// </summary>
        public static string MenuItemRecents {
            get {
                return ResourceManager.GetString("MenuItemRecents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tags: {0}.
        /// </summary>
        public static string MenuItemTotalTags {
            get {
                return ResourceManager.GetString("MenuItemTotalTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes to the currently loaded tag. Are you sure you want to cancel?.
        /// </summary>
        public static string MessageUnsavedCancel {
            get {
                return ResourceManager.GetString("MessageUnsavedCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Only newly added tags will show up on this table. If you have recently migrated, you will not see any tags here..
        /// </summary>
        public static string RecentsNoteAddedTimestampedOnly {
            get {
                return ResourceManager.GetString("RecentsNoteAddedTimestampedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search aliases/A.K.As?.
        /// </summary>
        public static string SearchEnableAliases {
            get {
                return ResourceManager.GetString("SearchEnableAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with....
        /// </summary>
        public static string SearchModeEndsWith {
            get {
                return ResourceManager.GetString("SearchModeEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match.
        /// </summary>
        public static string SearchModeExactMatch {
            get {
                return ResourceManager.GetString("SearchModeExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuzzy search.
        /// </summary>
        public static string SearchModeFuzzy {
            get {
                return ResourceManager.GetString("SearchModeFuzzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with....
        /// </summary>
        public static string SearchModeStartsWith {
            get {
                return ResourceManager.GetString("SearchModeStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tags found..
        /// </summary>
        public static string SearchMultipleResultsFound {
            get {
                return ResourceManager.GetString("SearchMultipleResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags found..
        /// </summary>
        public static string SearchNoResultsFound {
            get {
                return ResourceManager.GetString("SearchNoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One tag found..
        /// </summary>
        public static string SearchOneResultFound {
            get {
                return ResourceManager.GetString("SearchOneResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} tags..
        /// </summary>
        public static string StatusBlockBulkAddSuccess {
            get {
                return ResourceManager.GetString("StatusBlockBulkAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; loaded successfully..
        /// </summary>
        public static string StatusBlockDbLoadSuccessful {
            get {
                return ResourceManager.GetString("StatusBlockDbLoadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting tag hierarchy....
        /// </summary>
        public static string StatusBlockExportInProgress {
            get {
                return ResourceManager.GetString("StatusBlockExportInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported at &quot;{0}&quot;.
        /// </summary>
        public static string StatusBlockExportSuccessful {
            get {
                return ResourceManager.GetString("StatusBlockExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string StatusBlockReady {
            get {
                return ResourceManager.GetString("StatusBlockReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag &quot;{0}&quot; saved successfully..
        /// </summary>
        public static string StatusBlockTagSaveSuccessful {
            get {
                return ResourceManager.GetString("StatusBlockTagSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy Tree.
        /// </summary>
        public static string TabHierarchyTree {
            get {
                return ResourceManager.GetString("TabHierarchyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added.
        /// </summary>
        public static string TabRecentlyAdded {
            get {
                return ResourceManager.GetString("TabRecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Edited.
        /// </summary>
        public static string TabRecentlyEdited {
            get {
                return ResourceManager.GetString("TabRecentlyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string TabSearch {
            get {
                return ResourceManager.GetString("TabSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Hierarchy Manager.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Add Tags....
        /// </summary>
        public static string TitleBulkAdd {
            get {
                return ResourceManager.GetString("TitleBulkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string TitlemportDialog {
            get {
                return ResourceManager.GetString("TitlemportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added/Edited Tags.
        /// </summary>
        public static string TitleRecents {
            get {
                return ResourceManager.GetString("TitleRecents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Tag Hierarchy Manager.
        /// </summary>
        public static string TitleWithDatabase {
            get {
                return ResourceManager.GetString("TitleWithDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes to the currently loaded tag. Do you want to save them now?.
        /// </summary>
        public static string UnsavedChangesMessage {
            get {
                return ResourceManager.GetString("UnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/FlakyBlueJay/TagHierarchyManager.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query to search for....
        /// </summary>
        public static string WatermarkSearchQuery {
            get {
                return ResourceManager.GetString("WatermarkSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases/A.K.As (Separated by semi-colons).
        /// </summary>
        public static string WatermarkTagAliases {
            get {
                return ResourceManager.GetString("WatermarkTagAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag bindings (Separated by semi-colons, e.g. genre; style).
        /// </summary>
        public static string WatermarkTagBindings {
            get {
                return ResourceManager.GetString("WatermarkTagBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name (required).
        /// </summary>
        public static string WatermarkTagName {
            get {
                return ResourceManager.GetString("WatermarkTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string WatermarkTagNotes {
            get {
                return ResourceManager.GetString("WatermarkTagNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag parents (Separated by semi-colons).
        /// </summary>
        public static string WatermarkTagParents {
            get {
                return ResourceManager.GetString("WatermarkTagParents", resourceCulture);
            }
        }
    }
}
